language: node_js
node_js:
  - '9'

install:
  - npm install
  - npm run fetch_types
  - npm run build

script:
  - npm run coveralls

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release